/*************************************************************
 * Programmer: Joseph
 * 
 * Class: CS40S
 * 
 * Assignment: Matrix Calculator
 * 
 * Purpose: Act as my view for the project
 * 
 * Input: Comes from GUI
 * 
 * Output: Result of matrix mathematics
 *************************************************************/
package matrixcalculator;

public class MatrixView extends javax.swing.JFrame {

        MatrixController controller = new MatrixController();
        
    /**
     * Creates new form MatrixView
     */
    public MatrixView() {
        initComponents();
    }

    
    /*
    Purpose: Register controller
    Input: Controller pointer
    Output: none
    */
    
        public void registerController(MatrixController c){
            controller = c;
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pane1Add = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        pane2Add = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        pane3Add = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calculateAdd = new javax.swing.JButton();
        quitAddition = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboRowAdd1 = new javax.swing.JComboBox<>();
        comboColAdd1 = new javax.swing.JComboBox<>();
        fillAdd1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fillAdd2 = new javax.swing.JButton();
        comboRowAdd2 = new javax.swing.JComboBox<>();
        comboColAdd2 = new javax.swing.JComboBox<>();
        clearAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pane1Subtract = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        pane2Subtract = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        pane3Subtract = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calculateSubtract = new javax.swing.JButton();
        quitSubract = new javax.swing.JButton();
        clearSub = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fillSub1 = new javax.swing.JButton();
        comboRowSub1 = new javax.swing.JComboBox<>();
        comboColSub1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fillSub2 = new javax.swing.JButton();
        comboRowSub2 = new javax.swing.JComboBox<>();
        comboColSub2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        pane1Multiply = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        pane2Multiply = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        pane3Multiply = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calculateProduct = new javax.swing.JButton();
        quitProduct = new javax.swing.JButton();
        clearProd = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fillProd1 = new javax.swing.JButton();
        comboRowProd1 = new javax.swing.JComboBox<>();
        comboColProd1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboRowProd2 = new javax.swing.JComboBox<>();
        comboColProd2 = new javax.swing.JComboBox<>();
        fillProd2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        pane1Transpose = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        pane2Transpose = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        comboRowTranspose = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        fillTranspose = new javax.swing.JButton();
        comboColTranspose = new javax.swing.JComboBox<>();
        Transpose = new javax.swing.JButton();
        clearTranspose = new javax.swing.JButton();
        quitTranspose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(pane1Add);
        pane1Add.setText("Choose criteria you want from the side panel");

        jScrollPane3.setViewportView(pane2Add);
        pane2Add.setText("Choose criteria you want from the side panel");

        jScrollPane4.setViewportView(pane3Add);

        jLabel1.setText("+");

        jLabel2.setText("=");

        calculateAdd.setText("Calculate");
        calculateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateAddActionPerformed(evt);
            }
        });

        quitAddition.setText("Quit");
        quitAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitAdditionActionPerformed(evt);
            }
        });

        jLabel7.setText("Rows");

        jLabel8.setText("Columns");

        comboRowAdd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColAdd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        fillAdd1.setText("Fill Table 1");
        fillAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillAdd1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Rows");

        jLabel10.setText("Columns");

        fillAdd2.setText("Fill Table 2");
        fillAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillAdd2ActionPerformed(evt);
            }
        });

        comboRowAdd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColAdd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        clearAdd.setText("Clear");
        clearAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(comboColAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboRowAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(fillAdd1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboColAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(fillAdd2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(47, 47, 47)
                                            .addComponent(comboRowAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calculateAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(quitAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(comboRowAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboColAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(fillAdd1)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(comboRowAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboColAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillAdd2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(calculateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quitAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Addition", jPanel1);

        jScrollPane2.setViewportView(pane1Subtract);
        pane1Subtract.setText("Choose criteria you want from the side panel");

        jScrollPane5.setViewportView(pane2Subtract);
        pane2Subtract.setText("Choose criteria you want from the side panel");

        jScrollPane6.setViewportView(pane3Subtract);

        jLabel3.setText("=");

        jLabel4.setText("-");

        calculateSubtract.setText("Calculate");
        calculateSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateSubtractActionPerformed(evt);
            }
        });

        quitSubract.setText("Quit");
        quitSubract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitSubractActionPerformed(evt);
            }
        });

        clearSub.setText("Clear");
        clearSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSubActionPerformed(evt);
            }
        });

        jLabel11.setText("Rows");

        jLabel12.setText("Column");

        fillSub1.setText("Fill Table 1");
        fillSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillSub1ActionPerformed(evt);
            }
        });

        comboRowSub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColSub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel13.setText("Rows");

        jLabel14.setText("Column");

        fillSub2.setText("Fill Table 2");
        fillSub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillSub2ActionPerformed(evt);
            }
        });

        comboRowSub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColSub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboColSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboRowSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(fillSub1))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboRowSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(comboColSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(fillSub2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(calculateSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(clearSub, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitSubract))
                    .addComponent(jScrollPane6))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(comboRowSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(comboColSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(fillSub1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(comboRowSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(comboColSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fillSub2)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculateSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearSub, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitSubract, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Subtarction", jPanel2);

        jScrollPane7.setViewportView(pane1Multiply);
        pane1Multiply.setText("Choose criteria you want from the side panel");

        jScrollPane8.setViewportView(pane2Multiply);
        pane2Multiply.setText("Choose criteria you want from the side panel");

        jScrollPane9.setViewportView(pane3Multiply);

        jLabel5.setText("=");

        jLabel6.setText("*");

        calculateProduct.setText("Multiply");
        calculateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateProductActionPerformed(evt);
            }
        });

        quitProduct.setText("Quit");
        quitProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitProductActionPerformed(evt);
            }
        });

        clearProd.setText("Clear");
        clearProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearProdActionPerformed(evt);
            }
        });

        jLabel15.setText("Rows");

        jLabel16.setText("Columns");

        fillProd1.setText("Fill Table 1");
        fillProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillProd1ActionPerformed(evt);
            }
        });

        comboRowProd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColProd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel17.setText("Rows");

        jLabel18.setText("Columns");

        comboRowProd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboColProd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        fillProd2.setText("Fill Table 2");
        fillProd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillProd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboColProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboRowProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(fillProd1))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboColProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboRowProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(fillProd2)))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(calculateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(comboRowProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(comboColProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(fillProd1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(comboRowProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(comboColProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fillProd2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Multiplication", jPanel3);

        jScrollPane10.setViewportView(pane1Transpose);
        pane1Transpose.setText("Choose criteria you want from the side panel");

        jScrollPane11.setViewportView(pane2Transpose);

        jLabel19.setText("Rows");

        comboRowTranspose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel20.setText("Columns");

        fillTranspose.setText("Fill Table");
        fillTranspose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillTransposeActionPerformed(evt);
            }
        });

        comboColTranspose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Transpose.setText("Transpose");
        Transpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransposeActionPerformed(evt);
            }
        });

        clearTranspose.setText("Clear");
        clearTranspose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTransposeActionPerformed(evt);
            }
        });

        quitTranspose.setText("Quit");
        quitTranspose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitTransposeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Transpose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitTranspose))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboColTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(fillTranspose))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addGap(37, 37, 37)
                                .addComponent(comboRowTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jScrollPane10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(comboRowTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(comboColTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(fillTranspose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitTranspose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearTranspose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transpose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transposition", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Purpose: get comboBox value   
        // Input: selected index
        // Output: item @ the index
    private int getItem(int x){
        
        int i = 0;
        
        switch(x){
            case 0: i = 1;
                    break;
            case 1: i = 2;
                    break;
            case 2: i = 3;
                    break;
            case 3: i = 4;
                    break;
            case 4: i = 5;
                    break;
            case 5: i = 6;
                    break;
            case 6: i = 7;
                    break;
            case 7: i = 8;
                    break;
            case 8: i = 9;
                    break;
            case 9: i = 10;
                    break;
            default: break;
        }
        
        return i;
    } // end get Item
    
  // Purpose: fill panes with arrays  
        // Input: arrays,row, column
        // Output: string
    private String fill(int [][] t, int row, int col){
        String f = "";
        
        for(int r = 0; r < row; r++){
            for(int c = 0; c < col; c++){
                f += t[r][c] + " ";
            }
            f += "\n";
        }
        
        return f;
    } // end fill
    
  // Purpose: clear all panes   
        // Input: none
        // Output: none   
    
    private void clear(){
        
        // default announcement
        String d = "Choose criteria you want from the side panel";
        
        // clear addition tab
        pane1Add.setText(d);
        pane2Add.setText(d);
        pane3Add.setText("");
        comboRowAdd1.setSelectedIndex(0);
        comboRowAdd2.setSelectedIndex(0);
        comboColAdd1.setSelectedIndex(0);
        comboColAdd2.setSelectedIndex(0);
        
        // clear subtraction pane
        pane1Subtract.setText(d);
        pane2Subtract.setText(d);
        pane3Subtract.setText("");
        comboRowSub1.setSelectedIndex(0);
        comboRowSub2.setSelectedIndex(0);
        comboColSub1.setSelectedIndex(0);
        comboColSub2.setSelectedIndex(0);
        
        // clear muoltiply pane
        pane1Multiply.setText(d);
        pane2Multiply.setText(d);
        pane3Multiply.setText("");
        comboRowProd1.setSelectedIndex(0);
        comboRowProd2.setSelectedIndex(0);
        comboColProd1.setSelectedIndex(0);
        comboColProd2.setSelectedIndex(0);
        
        // clear transposition pane
        pane1Transpose.setText(d);
        pane2Transpose.setText("");
        comboRowTranspose.setSelectedIndex(0);
        comboColTranspose.setSelectedIndex(0);
        
    } // end clear
    
    private void quitAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitAdditionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitAdditionActionPerformed

    private void quitSubractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitSubractActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitSubractActionPerformed

    private void calculateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateAddActionPerformed
    
        if(controller.t1Add.getRow() == controller.t2Add.getRow() && 
                controller.t1Add.getCol() == controller.t2Add.getCol()){
            
            String fill;
        
        
            // method call to acquire array as a string
            fill = fill(controller.calculateAdd(), controller.t3Add.getRow(),
                controller.t3Add.getCol());
    
            pane3Add.setText(fill);
        } else {
            pane3Add.setText("Matrices must be of similar dimensions for the "
                    + "addition to work :)");
        }
        
    }//GEN-LAST:event_calculateAddActionPerformed

    private void fillAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillAdd1ActionPerformed
        // fill pane 1
       int rowsA;
       int colsA;
       
       String fill;
       
    // pane 1
        
        rowsA = getItem(comboRowAdd1.getSelectedIndex());
        colsA = getItem(comboColAdd1.getSelectedIndex());
        
        // method call to acquire array as a string
        fill = fill(controller.addPane1(rowsA, colsA), rowsA, colsA);
        pane1Add.setText(fill);
    }//GEN-LAST:event_fillAdd1ActionPerformed

    private void fillAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillAdd2ActionPerformed
        // TODO add your handling code here:
       int rowsB;
       int colsB;
       
       String fill;
       
    // pane 1
        
        rowsB = getItem(comboRowAdd2.getSelectedIndex());
        colsB = getItem(comboColAdd2.getSelectedIndex());
        
        // method call to acquire array as a string
        fill = fill(controller.addPane2(rowsB, colsB), rowsB, colsB);
        
        pane2Add.setText(fill);
    }//GEN-LAST:event_fillAdd2ActionPerformed

    private void clearAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearAddActionPerformed

    private void clearSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSubActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearSubActionPerformed

    private void fillSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillSub1ActionPerformed
        // TODO add your handling code here:
       int rowsA;
       int colsA;
       
       String fill;
       
    // pane 1
        
        rowsA = getItem(comboRowSub1.getSelectedIndex());
        colsA = getItem(comboColSub1.getSelectedIndex());
        
        // method call to acquire array as a string
        fill = fill(controller.subPane1(rowsA, colsA), rowsA, colsA);
        pane1Subtract.setText(fill);
    }//GEN-LAST:event_fillSub1ActionPerformed

    private void fillSub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillSub2ActionPerformed
        // TODO add your handling code here:
       int rowsB;
       int colsB;
       
       String fill;
       
    // pane 1
        
        rowsB = getItem(comboRowSub2.getSelectedIndex());
        colsB = getItem(comboColSub2.getSelectedIndex());
        
        // method call to acquire array as a string
        fill = fill(controller.subPane2(rowsB, colsB), rowsB, colsB);
        
        pane2Subtract.setText(fill);
    }//GEN-LAST:event_fillSub2ActionPerformed

    private void calculateSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateSubtractActionPerformed
        // TODO add your handling code here:
        
            if(controller.t1Sub.getRow() == controller.t2Sub.getRow() && 
                controller.t1Sub.getCol() == controller.t2Sub.getCol()){
            
            String fill;
        
        // method call to acquire array as a string
            fill = fill(controller.calculateSub(), controller.t3Sub.getRow(),
                controller.t3Sub.getCol());
    
            pane3Subtract.setText(fill);
        } else {
            pane3Subtract.setText("Matrices must be of similar dimensions for the "
                    + "subtraction to work :)");
        }
    }//GEN-LAST:event_calculateSubtractActionPerformed

    private void fillProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillProd1ActionPerformed
        // TODO add your handling code here:
        int rows;
        int cols;

        String fill;

        rows = getItem(comboRowProd1.getSelectedIndex());
        cols = getItem(comboColProd1.getSelectedIndex());

        // method call to acquire array as a string
        fill = fill(controller.prodPane1(rows, cols), rows, cols);

        pane1Multiply.setText(fill);
    }//GEN-LAST:event_fillProd1ActionPerformed

    private void clearProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearProdActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearProdActionPerformed

    private void quitProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitProductActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitProductActionPerformed

    private void fillProd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillProd2ActionPerformed
        // TODO add your handling code here:
        
        int rows;
        int cols;

        String fill;

        rows = getItem(comboRowProd2.getSelectedIndex());
        cols = getItem(comboColProd2.getSelectedIndex());

        // method call to acquire array as a string
        fill = fill(controller.prodPane2(rows, cols), rows, cols);

        pane2Multiply.setText(fill);
    }//GEN-LAST:event_fillProd2ActionPerformed

    private void calculateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateProductActionPerformed
        // TODO add your handling code here:
        
         if( controller.t1Prod.getCol() == controller.t2Prod.getRow()){
            
            String fill;
        
        // method call to acquire array as a string
            fill = fill(controller.calculateProd(), controller.t3Prod.getRow(),
                controller.t3Prod.getCol());
    
            pane3Multiply.setText(fill);
        } else {
            pane3Multiply.setText("Columns for table 1 must equal rows of table"
                    + " 2 for operation to work :)");
        }
         
    }//GEN-LAST:event_calculateProductActionPerformed

    private void clearTransposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTransposeActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearTransposeActionPerformed

    private void quitTransposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitTransposeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitTransposeActionPerformed

    private void fillTransposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillTransposeActionPerformed
        // TODO add your handling code here:
        int rows;       // rows 
        int cols;       // columns
        
        String fill;    // holds info to be put up
        
        rows = getItem(comboRowTranspose.getSelectedIndex());      //get rows
        cols = getItem(comboColTranspose.getSelectedIndex());      // get cols
        
        // method call to acquire array as a string
        fill = fill(controller.transposePane1(rows, cols), rows, cols); 
        
        pane1Transpose.setText(fill);   // send text to resultant pane
    }//GEN-LAST:event_fillTransposeActionPerformed

    private void TransposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransposeActionPerformed
        // TODO add your handling code here:
        
        String fill;
        
        
            // convert array to string
            fill = fill(controller.transpose(), controller.t2Transpose.getRow(),
                controller.t2Transpose.getCol());
    
            pane2Transpose.setText(fill);
    }//GEN-LAST:event_TransposeActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Transpose;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateAdd;
    private javax.swing.JButton calculateProduct;
    private javax.swing.JButton calculateSubtract;
    private javax.swing.JButton clearAdd;
    private javax.swing.JButton clearProd;
    private javax.swing.JButton clearSub;
    private javax.swing.JButton clearTranspose;
    private javax.swing.JComboBox<String> comboColAdd1;
    private javax.swing.JComboBox<String> comboColAdd2;
    private javax.swing.JComboBox<String> comboColProd1;
    private javax.swing.JComboBox<String> comboColProd2;
    private javax.swing.JComboBox<String> comboColSub1;
    private javax.swing.JComboBox<String> comboColSub2;
    private javax.swing.JComboBox<String> comboColTranspose;
    private javax.swing.JComboBox<String> comboRowAdd1;
    private javax.swing.JComboBox<String> comboRowAdd2;
    private javax.swing.JComboBox<String> comboRowProd1;
    private javax.swing.JComboBox<String> comboRowProd2;
    private javax.swing.JComboBox<String> comboRowSub1;
    private javax.swing.JComboBox<String> comboRowSub2;
    private javax.swing.JComboBox<String> comboRowTranspose;
    private javax.swing.JButton fillAdd1;
    private javax.swing.JButton fillAdd2;
    private javax.swing.JButton fillProd1;
    private javax.swing.JButton fillProd2;
    private javax.swing.JButton fillSub1;
    private javax.swing.JButton fillSub2;
    private javax.swing.JButton fillTranspose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane pane1Add;
    private javax.swing.JTextPane pane1Multiply;
    private javax.swing.JTextPane pane1Subtract;
    private javax.swing.JTextPane pane1Transpose;
    private javax.swing.JTextPane pane2Add;
    private javax.swing.JTextPane pane2Multiply;
    private javax.swing.JTextPane pane2Subtract;
    private javax.swing.JTextPane pane2Transpose;
    private javax.swing.JTextPane pane3Add;
    private javax.swing.JTextPane pane3Multiply;
    private javax.swing.JTextPane pane3Subtract;
    private javax.swing.JButton quitAddition;
    private javax.swing.JButton quitProduct;
    private javax.swing.JButton quitSubract;
    private javax.swing.JButton quitTranspose;
    // End of variables declaration//GEN-END:variables
}
